# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class cadUsuario(object):
    """
    A classe cadUsuario e responsavel por cadastrar um usuario

    O usuario e cadastrado no sistema atraves dessa classe com suas devidas informacoes

    """
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 500)
        MainWindow.setStyleSheet("background-color: rgb(255, 144, 134);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Login = QtWidgets.QLabel(self.centralwidget)
        self.label_Login.setGeometry(QtCore.QRect(90, 90, 451, 41))
        self.label_Login.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Matura MT Script Capitals")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_Login.setFont(font)
        self.label_Login.setStyleSheet("\n"
"color: rgb(86, 33, 85);\n"
"font: 22pt \"Matura MT Script Capitals\";\n"
"")
        self.label_Login.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_Login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Login.setObjectName("label_Login")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 350, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(227, 184, 178);\n"
"border-color: rgb(230, 89, 91);\n"
"font: 12pt \"Nirmala UI\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 210, 51, 21))
        self.label_2.setStyleSheet("font: 12pt \"Nirmala UI\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 300, 281, 31))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 300, 51, 21))
        self.label_4.setStyleSheet("font: 12pt \"Nirmala UI\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 200, 281, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(130, 350, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("\n"
"background-color: rgb(227, 184, 178);\n"
"border-color: rgb(230, 89, 91);\n"
"font: 12pt \"Nirmala UI\";")
        self.pushButton_1.setObjectName("pushButton_1")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(130, 160, 51, 21))
        self.label_1.setStyleSheet("font: 12pt \"Nirmala UI\";")
        self.label_1.setObjectName("label_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(190, 150, 281, 31))
        self.lineEdit_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 250, 151, 21))
        self.label_3.setStyleSheet("font: 12pt \"Nirmala UI\";")
        self.label_3.setObjectName("label_3")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_3.setGeometry(QtCore.QRect(190, 250, 281, 31))
        self.dateEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(260, 130, 118, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Login.setText(_translate("MainWindow", "<html><head/><body><p>Cadastro</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "CADASTRAR"))
        self.label_2.setText(_translate("MainWindow", "E-mail:"))
        self.label_4.setText(_translate("MainWindow", "Senha:"))
        self.pushButton_1.setText(_translate("MainWindow", "VOLTAR"))
        self.label_1.setText(_translate("MainWindow", "Nome:"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Data de Nascimento:</p></body></html>"))
